clear;

%Part1: Use the coefficients specified by us to build a low-pass filter.
%combined with
%Part2: Use the matlab function 'fir1()' to generate a low-pass filter.
fileID_coefficient = fopen('coefficient.txt','r');
formatSpec = '%f';
size_coefficient = [1 Inf];
our_low_pass_filter = fscanf(fileID_coefficient,formatSpec,size_coefficient);
fclose(fileID_coefficient);
H_our_low_pass = fftshift(fft(our_low_pass_filter));
H_our_low_pass_abs = abs(H_our_low_pass);

h = fir1(28, 6/24); %FIR generated by Matlab
H_low_pass_generated_by_matlab = fftshift(fft(h));
H_low_pass_generated_by_matlab_abs = abs(H_low_pass_generated_by_matlab);
ww = linspace(-24000, 24000, 29)';

figure
subplot(1,2,1), plot(ww, H_our_low_pass_abs);
axis([0 24000 0 1.5])
xlabel('frequency, Hz')
ylabel('Magnitude')
title('Our Low-Pass filter, with sample rate = 48kHz')
subplot(1,2,2), plot(ww, H_low_pass_generated_by_matlab_abs);
axis([0 24000 0 1.5])
xlabel('frequency, Hz')
ylabel('Magnitude')
title('Low-Pass filter generated by Matlab, with sample rate = 48kHz')


%Part3: inputting the test_input signal, which is provided by the CMSIS example, our low-pass filter.
fileID = fopen('input_1k_and_15k.txt','r'); %1k and 15k input signal
formatSpec = '%f';
size_of_input = [1 Inf];
test_input = fscanf(fileID,formatSpec,size_of_input);
fclose(fileID);
for i=1:320
    test_input_list(i)=test_input(i);
end
test_input_fourier_abs=abs(fftshift(fft(test_input_list)));
www = linspace(-24000, 24000, 320)';

figure
subplot(1,2,1), plot(test_input_list);
xlabel('320 points; sample rate = 48kHz ')
ylabel('Sampled values')
title('Test input signal, in time domain')
subplot(1,2,2), plot(www, test_input_fourier_abs);
axis([0 24000 0 150]) 
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Test input signal, in frequency domain')


%We test if the given test_output really corresponds to the output filtered by filters.
fileID_test_output = fopen('output_1k_and_15k.txt','r');
formatSpec = '%f';
size_test_output = [1 Inf];
test_output_given_by_Mbed = fscanf(fileID_test_output,formatSpec,size_test_output);
fclose(fileID_test_output);
test_output_freq_abs = abs(fftshift(fft(test_output_given_by_Mbed)));
figure 
subplot(1,2,1), plot(test_output_given_by_Mbed);
xlabel('320 points; sample rate = 48kHz for the test input')
ylabel('Values')
title('Test output signal given by Mbed, in time domain')
subplot(1,2,2), plot(www, test_output_freq_abs);
axis([0 24000 0 150]) 
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Test output signal given by Mbed, in frequency domain')



%Part4: check the output signals generated by our LP filter and by Matlab's
%filter, see if the results are the same.
test_output_signal_by_matlab_filter = filter(h,1,test_input_list);
test_output_fourier_by_matlab_abs=abs(fftshift(fft(test_output_signal_by_matlab_filter)));


test_output_signal_by_our_LP_filter = filter(our_low_pass_filter,1,test_input_list);
test_output_fourier_by_our_LP_abs=abs(fftshift(fft(test_output_signal_by_our_LP_filter)));


figure
subplot(2,2,1), plot(test_output_signal_by_our_LP_filter);
xlabel('320 points; sample rate = 48kHz for the input signal')
ylabel('Values')
title('Test output signal generated by our Low-Pass filter, in time domain')
subplot(2,2,2), plot(www, test_output_fourier_by_our_LP_abs);
axis([0 24000 0 150]) 
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Test output signal generated by our Low-Pass filter, in frequency domain')

subplot(2,2,3), plot(test_output_signal_by_matlab_filter);
xlabel('320 points; sample rate = 48kHz for the input signal')
ylabel('Values')
title("Test output signal generated by Matlab's Low-Pass filter, in time domain")
subplot(2,2,4), plot(www, test_output_fourier_by_matlab_abs);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title("Test output signal generated by Matlab's Low-Pass filter, in frequency domain")
axis([0 24000 0 150]) 
%Untill now, verification done.


%Part5: Process our Mbed's gyro signal.
fileID = fopen('newest_gyro_input.txt','r'); %new gyro input
formatSpec = '%f';
gyro_input_size = [3 320];
gyro_input = fscanf(fileID,formatSpec,gyro_input_size);
fclose(fileID);

for i=1:320
    x(i) = gyro_input(1,i);
    y(i) = gyro_input(2,i);
    z(i) = gyro_input(3,i);
end

figure 
subplot(1,3,1), plot(x)
xlabel('320 points; sample rate = 100Hz')
ylabel('Sampled values')
title('Input from mbed, gyroX, time domain');
subplot(1,3,2), plot(y)
xlabel('320 points; sample rate = 100Hz')
ylabel('Sampled values')
title('Input from mbed, gyroY, time domain');
subplot(1,3,3), plot(z)
xlabel('320 points; sample rate = 100Hz')
ylabel('Sampled values')
title('Input from mbed, gyroZ, time domain');



Xdft = fftshift(fft(x));
Xmagnitude = abs(Xdft);
Ymagnitude = abs((fftshift(fft(y))));
Zmagnitude = abs((fftshift(fft(z))));
w = linspace(-50, 50, 320)'; %since our sampling frequency is 100 hz.

figure
subplot(1,3,1), plot(w, Xmagnitude);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Frequency domain of input gyro X signal');
axis([0 50 0 5*10^6])
%hold on;
subplot(1,3,2), plot(w, Ymagnitude);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Frequency domain of input gyro Y signal');
axis([0 50 0 2*10^7])
%hold on;
subplot(1,3,3), plot(w, Zmagnitude);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Frequency domain of input gyro Z signal');
axis([0 50 0 5*10^6])

%%%



h = fir1(28, 6/24); %FIR generated by Matlab

fileIDD = fopen('newest_gyro_output.txt','r');
formatSpec = '%f';
sizeB = [3 320];
gyro_output_by_mbed = fscanf(fileIDD,formatSpec,sizeB);

for i=1:320
    x_output_by_mbed(i) = gyro_output_by_mbed(1,i);
    y_output_by_mbed(i) = gyro_output_by_mbed(2,i);
    z_output_by_mbed(i) = gyro_output_by_mbed(3,i);
end
figure 
subplot(1,3,1), plot(x_output_by_mbed)
xlabel('320 points; sample rate = 100Hz for the input signal')
ylabel('Values')
title('Output from mbed, gyroX');
subplot(1,3,2), plot(y_output_by_mbed)
xlabel('320 points; sample rate = 100Hz for the input signal')
ylabel('Values')
title('Output from mbed, gyroY');
subplot(1,3,3), plot(z_output_by_mbed)
xlabel('320 points; sample rate = 100Hz for the input signal')
ylabel('Values')
title('Output from mbed, gyroZ');


x_output_by_matlab = filter(h, 1, x);
y_output_by_matlab = filter(h, 1, y);
z_output_by_matlab = filter(h, 1, z);
figure
subplot(1,3,1), plot(x_output_by_matlab)
xlabel('320 points; sample rate = 100Hz for the input signal')
ylabel('Values')
title('Output from matlab, gyroX');
subplot(1,3,2), plot(y_output_by_matlab)
xlabel('320 points; sample rate = 100Hz for the input signal')
ylabel('Values')
title('Output from matlab, gyroY');
subplot(1,3,3), plot(z_output_by_matlab)
xlabel('320 points; sample rate = 100Hz for the input signal')
ylabel('Values')
title('Output from matlab, gyroZ');


%We compare the frequency domain of different outputs.
X_output_mbed_freq_magnitude = abs((fftshift(fft(x_output_by_mbed))));
Y_output_mbed_freq_magnitude = abs((fftshift(fft(y_output_by_mbed))));
Z_output_mbed_freq_magnitude = abs((fftshift(fft(z_output_by_mbed))));

X_output_matlab_freq_magnitude = abs((fftshift(fft(x_output_by_matlab))));
Y_output_matlab_freq_magnitude = abs((fftshift(fft(y_output_by_matlab))));
Z_output_matlab_freq_magnitude = abs((fftshift(fft(z_output_by_matlab))));
figure
subplot(2,3,1), plot(w, Xmagnitude);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Frequency domain of input gyro X signal');
axis([0 50 0 5*10^6])
subplot(2,3,2), plot(w, Ymagnitude);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Frequency domain of input gyro Y signal');
axis([0 50 0 2*10^7])
subplot(2,3,3), plot(w, Zmagnitude);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Frequency domain of input gyro Z signal');
axis([0 50 0 5*10^6])
subplot(2,3,4), plot(w, X_output_mbed_freq_magnitude);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Frequency domain of output gyro X signal(by Mbed)');
axis([0 50 0 5*10^6])
subplot(2,3,5), plot(w, Y_output_mbed_freq_magnitude);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Frequency domain of output gyro Y signal(by Mbed)');
axis([0 50 0 2*10^7])
subplot(2,3,6), plot(w, Z_output_mbed_freq_magnitude);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Frequency domain of output gyro Z signal(by Mbed)');
axis([0 50 0 5*10^6])

%%%
figure
subplot(2,3,1), plot(w, Xmagnitude);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Frequency domain of input gyro X signal');
axis([0 50 0 5*10^6])
subplot(2,3,2), plot(w, Ymagnitude);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Frequency domain of input gyro Y signal');
axis([0 50 0 2*10^7])
subplot(2,3,3), plot(w, Zmagnitude);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Frequency domain of input gyro Z signal');
axis([0 50 0 5*10^6])
subplot(2,3,4), plot(w, X_output_matlab_freq_magnitude);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Frequency domain of output gyro X signal(by Matlab)');
axis([0 50 0 5*10^6])
subplot(2,3,5), plot(w, Y_output_matlab_freq_magnitude);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Frequency domain of output gyro Y signal(by Matlab)');
axis([0 50 0 2*10^7])
subplot(2,3,6), plot(w, Z_output_matlab_freq_magnitude);
xlabel('Frequency, Hz')
ylabel('Magnitude')
title('Frequency domain of output gyro Z signal(by Matlab)');
axis([0 50 0 5*10^6])



